- hosts: localhost
  tasks:
    - name: Creating security group
      ec2_group:
        name: "shona"
        description: SG for nginx project
        vpc_id: vpc-f58b4d9e
        region: ap-south-1
        rules:
          - proto: tcp
            ports:
              - 8080
              - 80
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 8080, 80, 22
      register: sg

    - name: Launching EC2 instance
      ec2:
        key_name: Shona
        instance_type: t2.micro
        image: ami-04db49c0fb2215364
        group: shona
        count: 1
        region: ap-south-1
        vpc_subnet_id: subnet-b712fedc
        assign_public_ip: yes
        instance_tags:
          Name: "Docker-Nginx"  
        wait: yes
      register: instancee

    - name: printing output
      debug:
        var : instancee['instances'][0]['public_ip']

    - name: Writing IPs to inventory
      blockinfile:
        path: inventory
        block: |
          {{ instancee['instances'][0]['public_ip'] }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/ws/Shona.pem


